- 1.1.14
- _NAME: G733 Gaming Headset
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, rgb_control, rgb_zone_, brightness_control,
    per-key-lighting, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, m-key-leds,
    mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params]
  _battery: 7968
  _modelId: 0AFE00000000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _unitId: FFFFFFFF
  adc_power_management: 15
  divert-gkeys: false
  equalizer: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}
  led_control: 0
  led_zone_1: !LEDEffectSetting {ID: 1, color: 0, ramp: 0}
  led_zone_2: !LEDEffectSetting {ID: 0}
  sidetone: 0
