- 1.1.11+dfsg-2
- _NAME: G733 Gaming Headset
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params]
  _battery: 7968
  _modelId: 0AFE00000000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _unitId: FFFFFFFF
  adc_power_management: 0xf
  divert-gkeys: false
  equalizer: {0x0: 0x0, 0x1: 0x0, 0x2: 0x0, 0x3: 0x0, 0x4: 0x0, 0x5: 0x0, 0x6: 0x0, 0x7: 0x0, 0x8: 0x0, 0x9: 0x0}
  led_control: 0x0
  led_zone_1: !LEDEffectSetting {ID: 0x1, color: 0x0, ramp: 0x0}
  led_zone_2: !LEDEffectSetting {ID: 0x0}
  sidetone: 0x0
