[general]
fullscreen = true
early-exit = true
corner-roundness = 12
initial-tool = "pointer"
copy-command = "wl-copy"
annotation-size-factor = 1
action-on-enter = "save-to-clipboard"
save-after-copy = false
default-hide-toolbars = false
primary-highlighter = "freehand"
disable-notifications = false

[font]
# family = "Roboto"
# style = "Bold"
family = "OpenDyslexic Nerd Font"
style = ""

[color-palette]
palette = [
  "#FF0000",
  "#FF8800",
  "#FFFF00",
  "#00FF00",
  "#0000FF",
  "#884400",
  "#FF00FF",
  "#FFFFFF",
  "#000000",
]
custom = []
